import type { ExhibitorDashboard } from "@concourse/api-client";
import type { ReactNode } from "react";

export function DashboardScreen({ dashboard }: { dashboard: ExhibitorDashboard }) {
  const feed = dashboard.intelligenceFeed;
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6"><header><p className="text-sm font-medium text-secondary">Exhibitor intelligence</p><h1 className="mt-1 text-2xl font-semibold text-primary">Intelligence feed</h1><p className="mt-2 text-secondary">Newly shared attendee information for your active relationships.</p></header>
    <section aria-label="Intelligence feed" className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric label="Profiles enriched" value={feed.profilesEnriched} /><Metric label="Complete profiles" value={feed.completeProfiles} /><Metric label="Enrichment events" value={feed.items.length} /></section>
    <Panel title="Profile enrichment">{feed.items.length ? <ol className="space-y-4">{feed.items.map(item => <li className="border-l-2 border-strong pl-4" key={item.id}><p className="font-medium text-primary">{item.label}</p><time className="text-sm text-muted">{dateTime(item.at)}</time></li>)}</ol> : <Empty detail="Profile updates shared by attendees will appear here." />}</Panel>
    <section className="grid gap-6 lg:grid-cols-2"><Panel title="Relationship pipeline"><div className="grid grid-cols-2 gap-3"><Metric label="New" value={dashboard.pipeline.new} /><Metric label="Active" value={dashboard.pipeline.active} /><Metric label="Returning" value={dashboard.pipeline.returning} /><Metric label="Needs follow-up" value={dashboard.pipeline.needsFollowUp} /></div></Panel><Panel title="Booth performance snapshot"><div className="grid grid-cols-2 gap-3"><Metric label="QR scans" value={dashboard.performance.qrScans} /><Metric label="Relationships" value={dashboard.performance.relationshipsCreated} /><Metric label="Returning visitors" value={dashboard.performance.returningVisitors} /><Metric label="Profile completion" value={`${dashboard.performance.profileCompletion}%`} /><Metric label="Form completion" value={`${dashboard.performance.formCompletionRate}%`} /></div></Panel></section>
    <section className="grid gap-6 lg:grid-cols-2"><Panel title="Recent activity">{dashboard.recentActivity.length ? <ol className="space-y-4">{dashboard.recentActivity.map(activity => <li className="border-l-2 border-strong pl-4" key={`${activity.type}-${activity.id}`}><p className="font-medium text-primary">{activity.label}</p><time className="text-sm text-muted">{dateTime(activity.at)}</time></li>)}</ol> : <Empty detail="New scans, submissions, notes, and shared profile updates will appear here." />}</Panel><Panel title="Relationships requiring attention">{dashboard.attention.length ? <ul className="space-y-4">{dashboard.attention.map(item => <li className="rounded-lg bg-sunken p-3" key={item.relationshipId}><p className="font-medium text-primary">{item.attendeeName ?? "Attendee profile"}</p><p className="mt-1 text-sm text-secondary">{item.reasons.join(" · ")}</p></li>)}</ul> : <Empty detail="No relationships need attention right now." />}</Panel></section>
  </main>;
}

function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-xl border border-strong bg-surface p-5 sm:p-6"><h2 className="mb-4 text-lg font-semibold text-primary">{title}</h2>{children}</section>; }
function Metric({ label, value }: { label: string; value: number | string }) { return <div className="rounded-xl border border-strong bg-surface p-4"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-xl font-semibold text-primary">{value}</p></div>; }
function Empty({ detail }: { detail: string }) { return <p className="rounded-lg bg-sunken p-4 text-sm text-secondary">{detail}</p>; }
function dateTime(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
