import type { RelationshipWorkspace } from "@concourse/api-client";
import { NotesPanel } from "./notes-panel";

export function WorkspaceScreen({ workspace, organizationId }: { workspace: RelationshipWorkspace; organizationId: string }) {
  const shared = workspace.attendee.consentStatus === "shared";
  const attendee = workspace.attendee;
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
    <header className="rounded-xl border border-strong bg-surface p-5 sm:p-6">
      <div className="flex items-start gap-4"><div aria-hidden className="flex size-12 shrink-0 items-center justify-center rounded-full bg-sunken text-sm font-semibold text-primary">{initials(attendee.name)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="truncate text-2xl font-semibold text-primary">{attendee.name ?? "Attendee profile"}</h1><Status label={shared ? "Profile shared" : "Profile not shared"} tone={shared ? "positive" : "muted"} /></div><p className="mt-1 text-secondary">{shared ? [attendee.title, attendee.company].filter(Boolean).join(" · ") || "Professional details not yet provided" : "Contact and profile details are hidden until shared."}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm text-secondary"><span>{shared ? attendee.industry ?? "Industry not provided" : "Consent required"}</span><span>{shared ? attendee.contact.email ?? "Contact not provided" : "Consent required"}</span><span>Profile {attendee.profileCompleteness}% complete</span><span>Relationship {workspace.relationship.status}</span></div></div></div>
    </header>
    <section aria-label="Relationship summary" className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Interactions" value={String(workspace.summary.interactionCount)} /><Metric label="Notes" value={String(workspace.summary.noteCount)} /><Metric label="First interaction" value={dateTime(workspace.relationship.firstInteractionAt)} /><Metric label="Latest interaction" value={dateTime(workspace.summary.lastActivityAt)} /></section>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><section className="rounded-xl border border-strong bg-surface p-5 sm:p-6"><h2 className="text-lg font-semibold text-primary">Interaction timeline</h2>{workspace.timeline.length === 0 ? <Empty title="No submissions yet" detail="New visitor and exhibitor-assisted interactions will appear here." /> : <ol className="mt-5 space-y-5 border-l border-strong pl-5">{workspace.timeline.map((entry) => <li className="relative" key={entry.id}><span aria-hidden className="absolute -left-[1.6rem] top-1 size-3 rounded-full border-2 border-surface bg-brand" /><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-medium text-primary">{entry.form.name}</h3><time className="text-sm text-muted">{dateTime(entry.submittedAt)}</time></div><p className="mt-1 text-sm text-secondary">{source(entry.interactionSource)}</p><dl className="mt-3 space-y-2">{entry.values.map((value) => <div className="grid gap-1 sm:grid-cols-3" key={value.fieldId}><dt className="text-sm text-muted">{String(value.field.label ?? value.field.key ?? "Response")}</dt><dd className="text-sm text-primary sm:col-span-2">{display(value.value)}</dd></div>)}</dl></li>)}</ol>}</section><NotesPanel initialNotes={workspace.notes} organizationId={organizationId} relationshipId={workspace.relationship.id} /></div>
  </main>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-strong bg-surface p-4"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-base font-medium text-primary">{value}</p></div>; }
function Status({ label, tone }: { label: string; tone: "positive" | "muted" }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${tone === "positive" ? "bg-status-success-subtle text-status-success" : "bg-sunken text-secondary"}`}>{label}</span>; }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="mt-5 rounded-lg bg-sunken p-4"><p className="font-medium text-primary">{title}</p><p className="mt-1 text-sm text-secondary">{detail}</p></div>; }
function initials(name: string | null) { return name?.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "?"; }
function source(value: string) { return value === "visitor_qr" ? "Visitor QR" : value === "exhibitor_device" ? "Exhibitor device" : value; }
function dateTime(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function display(value: unknown) { return value === null || value === undefined || value === "" ? "—" : typeof value === "string" ? value : JSON.stringify(value); }
